version: 1
roles:
  - Dueño
  - Socio
  - Independiente estructurado
  - Independiente informal
  - Empleado dependiente privado - GERENCIA
  - Empleado dependiente privado - ADMINISTRATIVO
  - Empleado dependiente privado - AUXILIAR
  - Empleado público
  - Técnico / operativo
  - Jornalero / eventual
  - No definido
